version: "3"
services:
  app:
    build: .
    container_name: challenge2_app
    expose:
      - "3000"

  webserver:
    image: nginx:latest
    container_name: challenge2_webserver
    ports:
      - "8080:8080"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
