version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:8080"

  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
