version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - webserver
  webserver:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
